const compras = [
  //     fecha, proveedor, recepcionista, id
  // articulo, cantidad en kg, descripción, total en kg, total en pesos.
  {
    id_compra: "0",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "222",
    cantidad: "312",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$1288",
  },
  {
    id_compra: "1",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "65",
    cantidad: "22",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$88",
  },
  {
    id_compra: "2",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "832",
    cantidad: "723",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$188",
  },
  {
    id_compra: "3",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "163",
    cantidad: "465",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$23488",
  },
  {
    id_compra: "4",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "34",
    cantidad: "543",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$4438",
  },
  {
    id_compra: "5",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "923",
    cantidad: "373",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$82348",
  },
  {
    id_compra: "6",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "663",
    cantidad: "938",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$2888",
  },
  {
    id_compra: "7",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "685",
    cantidad: "4543",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$138",
  },
  {
    id_compra: "8",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "322",
    cantidad: "2421",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$4576",
  },
  {
    id_compra: "9",
    fecha_compra: "12/12/2022",
    proveedor: "Proveedor 1",
    recepcionista: "Recepcionista 1",
    articulo: "342",
    cantidad: "893",
    descrip_compra: "Una descripcion de compra",
    total_kg: "20",
    total: "$274",
  },
];

export default compras;
