const deudores = [
  {
    fecha_deuda: "31/11/23",
    nombre: "Pedro",
    apellido: "Lopez",
    ventas_realizadas: '10',
    ventas_realizadas: '10',
    cantidad: 20,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$30',
    tot_gen: '$60',
  },

  {
    fecha_deuda: "30/11/23",
    nombre: "Juan",
    apellido: "Lopez",
    ventas_realizadas: '10',
    cantidad: 21,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$31',
    tot_gen: '$61',
  },

  {
    fecha_deuda: "29/11/23",
    nombre: "Pedro",
    apellido: "Jurez",
    ventas_realizadas: '10',
    cantidad: 22,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$32',
    tot_gen: '$62',
  },

  {
    fecha_deuda: "28/11/23",
    nombre: "Pedro",
    apellido: "Lauriente",
    ventas_realizadas: '10',
    cantidad: 23,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$33',
    tot_gen: '$63',
  },

  {
    fecha_deuda: "27/11/23",
    nombre: "Victoria",
    apellido: "Lopez",
    ventas_realizadas: '10',
    cantidad: 24,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$34',
    tot_gen: '$64',
  },

  {
    fecha_deuda: "26/11/23",
    nombre: "Ricardo",
    apellido: "Lopez",
    ventas_realizadas: '10',
    cantidad: 25,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$35',
    tot_gen: '$65',
  },

  {
    fecha_deuda: "25/11/23",
    nombre: "Esteban",
    apellido: "Garmendia",
    ventas_realizadas: '10',
    cantidad: 26,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$36',
    tot_gen: '$66',
  },

  {
    fecha_deuda: "24/11/23",
    nombre: "Sofia",
    apellido: "Perez",
    ventas_realizadas: '10',
    cantidad: 27,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$37',
    tot_gen: '$67',
  },

  {
    fecha_deuda: "23/11/23",
    nombre: "Selene",
    apellido: "Asturias",
    ventas_realizadas: '10',
    cantidad: 28,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$38',
    tot_gen: '$68',
  },

  {
    fecha_deuda: "22/11/23",
    nombre: "Juan",
    apellido: "Perez",
    ventas_realizadas: '10',
    cantidad: 29,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$39',
    tot_gen: '$69',
  },

  {
    fecha_deuda: "21/11/23",
    nombre: "Pedro",
    apellido: "Vilalta",
    ventas_realizadas: '10',
    cantidad: 30,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$40',
    tot_gen: '$70',
  },

  {
    fecha_deuda: "20/11/23",
    nombre: "Rodro",
    apellido: "Rodriguez",
    ventas_realizadas: '10',
    cantidad: 31,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$41',
    tot_gen: '$71',
  },
  {
    fecha_deuda: "19/11/23",
    nombre: "Ricardo",
    apellido: "Lopez",
    ventas_realizadas: '10',
    cantidad: 42,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$32',
    tot_gen: '$72',
  },

  {
    fecha_deuda: "18/11/23",
    nombre: "Esteban",
    apellido: "Garmendia",
    ventas_realizadas: '10',
    cantidad: 43,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$33',
    tot_gen: '$73',
  },
  {
    fecha_deuda: "17/11/23",
    nombre: "Ricardo",
    apellido: "Lopez",
    ventas_realizadas: '10',
    cantidad: 44,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$34',
    tot_gen: '$74',
  },

  {
    fecha_deuda: "16/11/23",
    nombre: "Esteban",
    apellido: "Garmendia",
    ventas_realizadas: '10',
    cantidad: 45,
    descripcion_productos: "Calidad Alta",
    tot_prod: '$35',
    tot_gen: '$75',
  },
];

export default deudores;
