const ventas = [
    {
        id_venta:'0',
        fecha:'12/12/2022',
        nombre:'Arturo',
        articulos:'Descartables',
        cantidad:'312',
        total:'$3212'
    },
    {
        id_venta:'1',
        fecha:'12/12/2022',
        nombre:'Eduardo',
        articulos:'Limpieza',
        cantidad:'65',
        total:'$8922'
    },
    {
        id_venta:'2',
        fecha:'12/12/2022',
        nombre:'Carlos',
        articulos:'Reciclaje',
        cantidad:'832',
        total:'$723'
    },
    {
        id_venta:'3',
        fecha:'12/12/2022',
        nombre:'Enzo',
        articulos:'Limpieza',
        cantidad:'163',
        total:'$465'
    },
    {
        id_venta:'4',
        fecha:'12/12/2022',
        nombre:'Ivana',
        articulos:'Plastico',
        cantidad:'34',
        total:'$543'
    },
    {
        id_venta:'5',
        fecha:'12/12/2022',
        nombre:'Agusto',
        articulos:'Vidrio',
        cantidad:'923',
        total:'$373'
    },
    {
        id_venta:'6',
        fecha:'12/12/2022',
        nombre:'Paula',
        articulos:'Descartables',
        cantidad:'663',
        total:'$938'
    },
    {
        id_venta:'7',
        fecha:'12/12/2022',
        nombre:'Alberto',
        articulos:'Limpieza',
        cantidad:'685',
        total:'$4543'
    },
    {
        id_venta:'8',
        fecha:'12/12/2022',
        nombre:'Ricardo',
        articulos:'Plastico',
        cantidad:'322',
        total:'$2421'
    },
    {
        id_venta:'9',
        fecha:'12/12/2022',
        nombre:'Micaela',
        articulos:'Reciclaje',
        cantidad:'342',
        total:'$893'
    },
]

export default ventas;